package view;

import classes.Aluno;
import dao.AlunoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marco
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrade = new javax.swing.JTable();
        btnCarregarBD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jblSelecionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo BD");
        getContentPane().setLayout(null);

        tblGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RGM", "Nome", "Nota 1", "Nota2"
            }
        ));
        tblGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGradeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGrade);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 11, 452, 275);

        btnCarregarBD.setText("Carregar BD");
        btnCarregarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarBDActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarregarBD);
        btnCarregarBD.setBounds(182, 304, 91, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Selecionado:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 360, 71, 14);
        getContentPane().add(jblSelecionado);
        jblSelecionado.setBounds(110, 360, 363, 15);

        setSize(new java.awt.Dimension(512, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarBDActionPerformed
        // TODO add your handling code here:
//        System.out.println("Clique");
        ArrayList<Aluno> lista = new AlunoDAO().listaAlunos();

        DefaultTableModel modelo = (DefaultTableModel) tblGrade.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getRgm(),  lista.get(i).getNome(),
                                       ("" + lista.get(i).getNota1()),
                                       ("" + lista.get(i).getNota2())});
        }
    }//GEN-LAST:event_btnCarregarBDActionPerformed

    private void tblGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGradeMouseClicked
        // TODO add your handling code here:
        if (tblGrade.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Nada selecionado");
        } else {
            int i = tblGrade.getSelectionModel().getMinSelectionIndex();
            String escolhido = "RGM: " + tblGrade.getModel().getValueAt(i, 0) + 
                                    "\n Nome: " + tblGrade.getModel().getValueAt(i, 1);
            JOptionPane.showMessageDialog(null, escolhido);
            jblSelecionado.setText(escolhido);
        }        
    }//GEN-LAST:event_tblGradeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarBD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblSelecionado;
    private javax.swing.JTable tblGrade;
    // End of variables declaration//GEN-END:variables
}
