
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marco
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRgm = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jrdAN = new javax.swing.JRadioButton();
        jrdLib = new javax.swing.JRadioButton();
        jrdPta = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados pessoais"));
        jPanel1.setLayout(null);

        jLabel1.setText("RGM:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 40, 14);

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 50, 14);
        jPanel1.add(txtRgm);
        txtRgm.setBounds(90, 30, 80, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(90, 60, 230, 20);

        groupRadio.add(jrdAN);
        jrdAN.setText("Anália Franco");
        jrdAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdANActionPerformed(evt);
            }
        });
        jPanel1.add(jrdAN);
        jrdAN.setBounds(20, 110, 110, 23);

        groupRadio.add(jrdLib);
        jrdLib.setText("Liberdade");
        jPanel1.add(jrdLib);
        jrdLib.setBounds(150, 110, 90, 23);

        groupRadio.add(jrdPta);
        jrdPta.setText("Paulista");
        jPanel1.add(jrdPta);
        jrdPta.setBounds(270, 110, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 360, 160);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(20, 200, 80, 23);

        lblResult.setText("O resultado vai aqui");
        getContentPane().add(lblResult);
        lblResult.setBounds(20, 240, 130, 20);

        setSize(new java.awt.Dimension(416, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jrdANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdANActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String Nome, RGM, Campus;
        RGM = txtRgm.getText();
        Nome = txtNome.getText();
        Campus ="";
        
       
        if(jrdAN.isSelected()){
            Campus = "Anália Franco";
        } 
        else if(jrdLib.isSelected()){
            Campus = "Liberdade";
        } 
        else if(jrdPta.isSelected()){
            Campus = "Paulista";
        } 
        JOptionPane.showMessageDialog(null, "Dados Pessoais: " + Nome + "\n" + Campus);
//        lblResult.setText(RGM);
//        btnEnviar.setText("Palmeiras");
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup groupRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrdAN;
    private javax.swing.JRadioButton jrdLib;
    private javax.swing.JRadioButton jrdPta;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRgm;
    // End of variables declaration//GEN-END:variables
}
